/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OrgRouteImport } from './routes/org'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOrgSettingsRouteImport } from './routes/_app/org-settings'
import { Route as AppDemoConvexRouteImport } from './routes/_app/demo/convex'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSettingsRoute = AppOrgSettingsRouteImport.update({
  id: '/org-settings',
  path: '/org-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoConvexRoute = AppDemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/org': typeof OrgRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/org-settings': typeof AppOrgSettingsRoute
  '/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRoutesByTo {
  '/org': typeof OrgRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/org-settings': typeof AppOrgSettingsRoute
  '/': typeof AppIndexRoute
  '/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/org': typeof OrgRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/org-settings': typeof AppOrgSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/org-settings'
    | '/demo/convex'
  fileRoutesByTo: FileRoutesByTo
  to: '/org' | '/sign-in' | '/sign-up' | '/org-settings' | '/' | '/demo/convex'
  id:
    | '__root__'
    | '/_app'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/_app/org-settings'
    | '/_app/'
    | '/_app/demo/convex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OrgRoute: typeof OrgRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org-settings': {
      id: '/_app/org-settings'
      path: '/org-settings'
      fullPath: '/org-settings'
      preLoaderRoute: typeof AppOrgSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/convex': {
      id: '/_app/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof AppDemoConvexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOrgSettingsRoute: typeof AppOrgSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemoConvexRoute: typeof AppDemoConvexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgSettingsRoute: AppOrgSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemoConvexRoute: AppDemoConvexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OrgRoute: OrgRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
